{"name": "Test job cities from the yopeso website against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occurred", "trace": "get_job_details = ((['DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive IT Services', 'Incident Manager', 'Java deve...eso', 'Yopeso', 'Yopeso', 'Yopeso', 'Yopeso', ...], ['remote', 'remote', 'remote', 'remote', 'remote', 'remote', ...]))\n\n    @pytest.mark.regression\n    @pytest.mark.API\n    def test_yopeso_city_api(get_job_details):\n        allure.dynamic.title(f\"Test job cities from the {company_name} website against Peviitor API Response\")\n    \n        scraped_jobs_data, peviitor_jobs_data = get_job_details\n        with allure.step(\"Step 1: Get job cities and titles from the scraper\"):\n            job_cities_scraper = scraped_jobs_data[1]\n            job_titles_scraper = scraped_jobs_data[0]\n    \n        with allure.step(\"Step 2: Get job cities and titles from the Peviitor API\"):\n            job_cities_peviitor = peviitor_jobs_data[1]\n            job_titles_peviitor = peviitor_jobs_data[0]\n    \n        with allure.step(\"Step 3: Compare job cities from scraper response against Peviitor API Response\"):\n            allure.attach(f\"Expected Results: {job_cities_scraper}\", name=\"Expected Results\")\n            allure.attach(f\"Actual Results: {job_cities_peviitor}\", name=\"Actual Results\")\n>           TestUtils().check_job_cities(job_cities_scraper, job_cities_peviitor, job_titles_scraper, job_titles_peviitor)\n\ntests/Test_API_Suite/test_yopeso.py:72: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.TestUtils object at 0x7f1be2d45f90>\nexpected_cities = [['Iasi'], ['Cluj-Napoca'], ['Bucuresti'], ['Cluj Napoca'], ['Cluj-Napoca'], ['Iasi'], ...]\nactual_cities = [['Iasi'], ['Cluj-Napoca'], ['Bucuresti'], ['Cluj-Napoca'], ['Cluj-Napoca'], ['Iasi'], ...]\njob_titles_scraper = ['DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive IT Services', 'Incident Manager', 'Java developer/Fullstack Engineer', 'Javascript Fullstack Engineer', ...]\napi_job_titles = ['DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive IT Services', 'Incident Manager', 'Java developer/Fullstack Engineer', 'Javascript Fullstack Engineer', ...]\n\n    def check_job_cities(self, expected_cities, actual_cities, job_titles_scraper, api_job_titles):\n        if not expected_cities:\n            msg = f\"Scraper is not grabbing any job cities\"\n            allure.step(msg)\n            raise AssertionError(msg)\n    \n        msg = \"An unknown error occurred\"\n    \n        # Check jobs from scraper against the peviitor api\n        scraper_actual_cities, scraper_job_titles = self.get_different_items(expected_cities, actual_cities, job_titles_scraper)\n    \n        if scraper_actual_cities:\n            msg = f\"Peviitor is missing job cities for the following job titles: {scraper_job_titles}\"\n            allure.step(msg)\n            raise AssertionError(msg)\n        else:\n            # Check jobs from peviitor against the scraper response\n            peviitor_actual_cities, peviitor_job_titles = self.get_different_items(actual_cities, expected_cities, api_job_titles)\n            if peviitor_actual_cities:\n                msg = f\"Peviitor is having extra job cities for the following job titles: {peviitor_job_titles}\"\n                allure.step(msg)\n                raise AssertionError(msg)\n    \n        allure.step(msg)\n>       assert expected_cities == actual_cities, msg\nE       AssertionError: An unknown error occurred\n\ntests/utils.py:151: AssertionError"}, "steps": [{"name": "Step 1: Get job cities and titles from the scraper", "status": "passed", "start": 1709356511897, "stop": 1709356511897}, {"name": "Step 2: Get job cities and titles from the Peviitor API", "status": "passed", "start": 1709356511897, "stop": 1709356511897}, {"name": "Step 3: Compare job cities from scraper response against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occurred\n", "trace": "  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_yopeso.py\", line 72, in test_yopeso_city_api\n    TestUtils().check_job_cities(job_cities_scraper, job_cities_peviitor, job_titles_scraper, job_titles_peviitor)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/utils.py\", line 151, in check_job_cities\n    assert expected_cities == actual_cities, msg\n"}, "attachments": [{"name": "Expected Results", "source": "25d68e20-4bc3-4b1e-bc54-37359285db8c-attachment.attach"}, {"name": "Actual Results", "source": "170a7302-7d04-4469-8945-8efb9af5629f-attachment.attach"}], "start": 1709356511897, "stop": 1709356511898}], "start": 1709356511897, "stop": 1709356511898, "uuid": "a86939a1-ef9f-4b8f-b76a-62c74afcb104", "historyId": "a8e2f1793df2b4d84082fec62edde753", "testCaseId": "a8e2f1793df2b4d84082fec62edde753", "fullName": "Test_API_Suite.test_yopeso#test_yopeso_city_api", "labels": [{"name": "tag", "value": "API"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "Test_API_Suite"}, {"name": "suite", "value": "test_yopeso"}, {"name": "host", "value": "fv-az588-658"}, {"name": "thread", "value": "2294-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_API_Suite.test_yopeso"}]}