{"name": "Test job companies from the company azur website against Peviitor", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured in the API job company name test case", "trace": "get_job_details = (['Operator sinteză chimică', 'Inginer protecția mediului'], [['Timisoara'], ['Timisoara']], ['Romania', 'Romania'], [...ariere/operator-sinteza-chimica', 'https://www.azur.ro/ro/cariere/inginer-protectia-mediului'], ['on-site', 'on-site'])\nscrape_ui = (<tests.Test_Selenium_Suite.seleniumutils.TestUtils object at 0x7f9e54fd57b0>, (['Operator sinteză chimică', 'Inginer ...502ed3e4561bcbcb9103b1\", element=\"f.9134D0ACCD0E2D36FDC421DE0964B093.d.45378BA6E280596879C94E3DA0FAFF4F.e.43\")>], ...))\n\n    @pytest.mark.regression\n    @pytest.mark.ui\n    def test_azur_company_ui(get_job_details, scrape_ui):\n        allure.dynamic.title(f\"Test job companies from the company {company_name} website against Peviitor\")\n    \n        scraped_jobs_data = get_job_details\n        with allure.step(\"Step 1: Get expected job company names\"):\n            job_companies_scraper = [company_name] * len(scraped_jobs_data[4])\n        with allure.step(\"Step 2: Get actual job companies from the Peviitor\"):\n            # Grab the data from peviitor ui\n    \n            testutils, job_details = scrape_ui[0], scrape_ui[1]\n            job_companies_peviitor = job_details[3]\n    \n        with allure.step(f\"Step 3: Compare job companies from the company {company_name} website against Peviitor\"):\n            allure.attach(f\"Expected Results: {job_companies_scraper}\", name=\"Scraper Expected Results\")\n            allure.attach(f\"Actual Results: {job_companies_peviitor}\", name=\"Peviitor Actual Results\")\n>           testutils.check_ui_job_company(job_companies_scraper, job_companies_peviitor)\n\ntests/Test_Selenium_Suite/test_azur.py:152: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.Test_Selenium_Suite.seleniumutils.TestUtils object at 0x7f9e54fd57b0>\nexpected_company_name = ['azur', 'azur']\nactual_company_name = ['azur', 'azur', 'azur sa', 'azur sa', 'azur sa']\n\n    def check_ui_job_company(self, expected_company_name: list, actual_company_name: list):\n    \n        # Lowercase all items in list to ensure proper comparison\n        expected_company_name, actual_company_name = [name.lower() for name in expected_company_name], [name.lower() for name in actual_company_name]\n    \n        # If no actual company name is in the API\n        if not actual_company_name:\n            msg = f\"No results display the company name within the API Response\"\n            allure.step(msg)\n            raise AssertionError(msg)\n    \n        # If the actual company name in the api does not correspond to expected company name raise error\n        for actual_name, expected_name in zip(actual_company_name, expected_company_name):\n            if actual_name != expected_name:\n                msg = f\"Company name does not match for one of the job results from the API Response\"\n                allure.step(msg)\n                raise AssertionError(msg)\n    \n>       assert expected_company_name[:len(actual_company_name)] == actual_company_name, \"An unknown error occured in the API job company name test case\"\nE       AssertionError: An unknown error occured in the API job company name test case\n\ntests/Test_Selenium_Suite/seleniumutils.py:293: AssertionError"}, "steps": [{"name": "Step 1: Get expected job company names", "status": "passed", "start": 1715404704127, "stop": 1715404704127}, {"name": "Step 2: Get actual job companies from the Peviitor", "status": "passed", "start": 1715404704127, "stop": 1715404704127}, {"name": "Step 3: Compare job companies from the company azur website against Peviitor", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured in the API job company name test case\n", "trace": "  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_Selenium_Suite/test_azur.py\", line 152, in test_azur_company_ui\n    testutils.check_ui_job_company(job_companies_scraper, job_companies_peviitor)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_Selenium_Suite/seleniumutils.py\", line 293, in check_ui_job_company\n    assert expected_company_name[:len(actual_company_name)] == actual_company_name, \"An unknown error occured in the API job company name test case\"\n"}, "attachments": [{"name": "Scraper Expected Results", "source": "945e73fc-97de-4af9-be1a-65571d2159aa-attachment.attach"}, {"name": "Peviitor Actual Results", "source": "d7c5bd8d-453e-4423-8a8e-aac7c4213751-attachment.attach"}], "start": 1715404704127, "stop": 1715404704127}], "start": 1715404704127, "stop": 1715404704128, "uuid": "d143c498-55ff-4267-a507-58714b8f92e7", "historyId": "f349ca595a17b7e0045148710ba4f3d3", "testCaseId": "f349ca595a17b7e0045148710ba4f3d3", "fullName": "Test_Selenium_Suite.test_azur#test_azur_company_ui", "labels": [{"name": "tag", "value": "ui"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "Test_Selenium_Suite"}, {"name": "suite", "value": "test_azur"}, {"name": "host", "value": "fv-az571-539"}, {"name": "thread", "value": "2280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Selenium_Suite.test_azur"}]}