{"name": "Test job companies from the company c4media website against Peviitor", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured in the API job company name test case", "trace": "get_job_details = ([], [], [], [], [])\nscrape_ui = (<tests.Test_Selenium_Suite.seleniumutils.TestUtils object at 0x7efd7b0bc040>, (['Administrative Assistant (full-time,...d09d6040c0255e98460e4d\", element=\"f.8C95BE7C62E83DEAB6FC3F13068B7789.d.8B08AD34387C3B1BC66859BCD854E96F.e.37\")>], ...))\n\n    @pytest.mark.regression\n    @pytest.mark.ui\n    def test_c4media_company_ui(get_job_details, scrape_ui):\n        allure.dynamic.title(f\"Test job companies from the company {company_name} website against Peviitor\")\n    \n        scraped_jobs_data = get_job_details\n        with allure.step(\"Step 1: Get expected job company names\"):\n            job_companies_scraper = [company_name] * len(scraped_jobs_data[4])\n        with allure.step(\"Step 2: Get actual job companies from the Peviitor\"):\n            # Grab the data from peviitor ui\n    \n            testutils, job_details = scrape_ui[0], scrape_ui[1]\n            job_companies_peviitor = job_details[3]\n    \n        with allure.step(f\"Step 3: Compare job companies from the company {company_name} website against Peviitor\"):\n            allure.attach(f\"Expected Results: {job_companies_scraper}\", name=\"Scraper Expected Results\")\n            allure.attach(f\"Actual Results: {job_companies_peviitor}\", name=\"Peviitor Actual Results\")\n>           testutils.check_ui_job_company(job_companies_scraper, job_companies_peviitor)\n\ntests/Test_Selenium_Suite/test_c4media.py:152: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.Test_Selenium_Suite.seleniumutils.TestUtils object at 0x7efd7b0bc040>\nexpected_company_name = [], actual_company_name = ['c4media', 'c4media']\n\n    def check_ui_job_company(self, expected_company_name: list, actual_company_name: list):\n    \n        # Lowercase all items in list to ensure proper comparison\n        expected_company_name, actual_company_name = [name.lower() for name in expected_company_name], [name.lower() for name in actual_company_name]\n    \n        # If no actual company name is in the API\n        if not actual_company_name:\n            msg = f\"No results display the company name within the API Response\"\n            allure.step(msg)\n            raise AssertionError(msg)\n    \n        # If the actual company name in the api does not correspond to expected company name raise error\n        for actual_name, expected_name in zip(actual_company_name, expected_company_name):\n            if actual_name != expected_name:\n                msg = f\"Company name does not match for one of the job results from the API Response\"\n                allure.step(msg)\n                raise AssertionError(msg)\n    \n>       assert expected_company_name[:len(actual_company_name)] == actual_company_name, \"An unknown error occured in the API job company name test case\"\nE       AssertionError: An unknown error occured in the API job company name test case\n\ntests/Test_Selenium_Suite/seleniumutils.py:293: AssertionError"}, "steps": [{"name": "Step 1: Get expected job company names", "status": "passed", "start": 1712467030230, "stop": 1712467030230}, {"name": "Step 2: Get actual job companies from the Peviitor", "status": "passed", "start": 1712467030230, "stop": 1712467030230}, {"name": "Step 3: Compare job companies from the company c4media website against Peviitor", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured in the API job company name test case\n", "trace": "  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_Selenium_Suite/test_c4media.py\", line 152, in test_c4media_company_ui\n    testutils.check_ui_job_company(job_companies_scraper, job_companies_peviitor)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_Selenium_Suite/seleniumutils.py\", line 293, in check_ui_job_company\n    assert expected_company_name[:len(actual_company_name)] == actual_company_name, \"An unknown error occured in the API job company name test case\"\n"}, "attachments": [{"name": "Scraper Expected Results", "source": "058708fa-17bb-4634-a1ab-f09d67e24d8b-attachment.attach"}, {"name": "Peviitor Actual Results", "source": "f7b33b5f-3c1b-49b9-bfef-c70ba3e2bb09-attachment.attach"}], "start": 1712467030230, "stop": 1712467030230}], "start": 1712467030230, "stop": 1712467030230, "uuid": "2debab89-594a-4763-81a7-8dafa375ae7e", "historyId": "8d186585b1554fadc8e9085419e7d1e4", "testCaseId": "8d186585b1554fadc8e9085419e7d1e4", "fullName": "Test_Selenium_Suite.test_c4media#test_c4media_company_ui", "labels": [{"name": "tag", "value": "ui"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "Test_Selenium_Suite"}, {"name": "suite", "value": "test_c4media"}, {"name": "host", "value": "fv-az1202-671"}, {"name": "thread", "value": "2063-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Selenium_Suite.test_c4media"}]}