{"uuid": "c10bdfc6-c4e2-4d51-9af4-3e0093fd48a8", "children": ["8f2326c6-94e6-4470-b476-b297f96ea0ae", "646a3626-042d-47b0-8314-a5a3f80e1ad9", "9a66b945-fe74-44ab-ab1f-07350b35554f", "5c7b6019-0c61-4a7b-9b20-ab9341a0df39", "e7a7e099-a744-445c-b20b-7bbfa814a960", "524201d0-e9f3-4df1-b339-024ab1323ca4"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.catena.ro', port=443): Max retries exceeded with url: /cariere (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7faaa17db7c0>, 'Connection to www.catena.ro timed out. (connect timeout=None)'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pluggy-1.5.0-py3.10.egg/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pytest-7.4.3-py3.10.egg/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pytest-7.4.3-py3.10.egg/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_Selenium_Suite/test_catena.py\", line 15, in get_job_details\n    scraper_data = catenaScraper()\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/sites/catena_scraper.py\", line 25, in scraper\n    soup = GetStaticSoup(\"https://www.catena.ro/cariere\")\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/sites/__utils/req_bs4_shorts.py\", line 36, in __new__\n    response = session.get(link, headers=headers)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests-2.28.2-py3.10.egg/requests/sessions.py\", line 600, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests-2.28.2-py3.10.egg/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests-2.28.2-py3.10.egg/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests-2.28.2-py3.10.egg/requests/adapters.py\", line 553, in send\n    raise ConnectTimeout(e, request=request)\n"}, "start": 1716355547871, "stop": 1716355677789}], "start": 1716355547871, "stop": 1716355678221}