{"name": "Test job cities from the yopeso website against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occurred", "trace": "get_job_details = ((['C++/ QT Senior developer', 'Data Engineer', 'DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive...'Yopeso', 'Yopeso', 'Yopeso', 'Yopeso', ...], ['on-site', 'on-site', 'on-site', 'on-site', 'on-site', 'on-site', ...]))\n\n    @pytest.mark.regression\n    @pytest.mark.API\n    def test_yopeso_city_api(get_job_details):\n        allure.dynamic.title(f\"Test job cities from the {company_name} website against Peviitor API Response\")\n    \n        scraped_jobs_data, peviitor_jobs_data = get_job_details\n        with allure.step(\"Step 1: Get job cities and titles from the scraper\"):\n            job_cities_scraper = scraped_jobs_data[1]\n            job_titles_scraper = scraped_jobs_data[0]\n    \n        with allure.step(\"Step 2: Get job cities and titles from the Peviitor API\"):\n            job_cities_peviitor = peviitor_jobs_data[1]\n            job_titles_peviitor = peviitor_jobs_data[0]\n    \n        with allure.step(\"Step 3: Compare job cities from scraper response against Peviitor API Response\"):\n            allure.attach(f\"Scraper Expected Results: {job_cities_scraper}\", name=\"Expected Results\")\n            allure.attach(f\"Peviitor Actual Results: {job_cities_peviitor}\", name=\"Actual Results\")\n>           TestUtils().check_job_cities(job_cities_scraper, job_cities_peviitor, job_titles_scraper, job_titles_peviitor)\n\ntests/Test_API_Suite/test_yopeso.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.TestUtils object at 0x7efc1afab640>\nexpected_cities = [['Cluj-Napoca'], ['Cluj-Napoca'], ['Cluj-Napoca'], ['Cluj-Napoca'], ['Bucuresti'], ['Cluj Napoca'], ...]\nactual_cities = [['Cluj-Napoca'], ['Cluj-Napoca'], ['Cluj-Napoca'], ['Cluj-Napoca'], ['Bucuresti'], ['Cluj-Napoca'], ...]\njob_titles_scraper = ['C++/ QT Senior developer', 'Data Engineer', 'DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive IT Services', 'Incident Manager', ...]\napi_job_titles = ['C++/ QT Senior developer', 'Data Engineer', 'DevOps Engineer', 'Engineering Manager', 'Experienced Sales Executive IT Services', 'Incident Manager', ...]\n\n    def check_job_cities(self, expected_cities, actual_cities, job_titles_scraper, api_job_titles):\n        if not expected_cities:\n            msg = f\"Scraper is not grabbing any job cities\"\n            allure.step(msg)\n            raise AssertionError(msg)\n    \n        msg = \"An unknown error occurred\"\n    \n        # Check jobs from scraper against the peviitor api\n        scraper_actual_cities, scraper_job_titles = self.get_different_items(expected_cities, actual_cities, job_titles_scraper)\n    \n        if scraper_actual_cities:\n            msg = f\"Peviitor is missing job cities for the following job titles: {scraper_job_titles}\"\n            allure.step(msg)\n            raise AssertionError(msg)\n        else:\n            # Check jobs from peviitor against the scraper response\n            peviitor_actual_cities, peviitor_job_titles = self.get_different_items(actual_cities, expected_cities, api_job_titles)\n            if peviitor_actual_cities:\n                msg = f\"Peviitor is having extra job cities for the following job titles: {peviitor_job_titles}\"\n                allure.step(msg)\n                raise AssertionError(msg)\n    \n        allure.step(msg)\n>       assert expected_cities == actual_cities, msg\nE       AssertionError: An unknown error occurred\n\ntests/utils.py:151: AssertionError"}, "steps": [{"name": "Step 1: Get job cities and titles from the scraper", "status": "passed", "start": 1710738997661, "stop": 1710738997661}, {"name": "Step 2: Get job cities and titles from the Peviitor API", "status": "passed", "start": 1710738997661, "stop": 1710738997661}, {"name": "Step 3: Compare job cities from scraper response against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occurred\n", "trace": "  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/Test_API_Suite/test_yopeso.py\", line 71, in test_yopeso_city_api\n    TestUtils().check_job_cities(job_cities_scraper, job_cities_peviitor, job_titles_scraper, job_titles_peviitor)\n  File \"/home/runner/work/scrapers_Larisa_M16/scrapers_Larisa_M16/tests/utils.py\", line 151, in check_job_cities\n    assert expected_cities == actual_cities, msg\n"}, "attachments": [{"name": "Expected Results", "source": "a0a50085-f836-45a0-a25f-d8bcad323a78-attachment.attach"}, {"name": "Actual Results", "source": "51ec4d15-ac32-4a94-9e7f-607f914a235f-attachment.attach"}], "start": 1710738997661, "stop": 1710738997662}], "start": 1710738997661, "stop": 1710738997662, "uuid": "f25444e0-a044-41ca-9d40-09ce20ec8c88", "historyId": "a8e2f1793df2b4d84082fec62edde753", "testCaseId": "a8e2f1793df2b4d84082fec62edde753", "fullName": "Test_API_Suite.test_yopeso#test_yopeso_city_api", "labels": [{"name": "tag", "value": "API"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "Test_API_Suite"}, {"name": "suite", "value": "test_yopeso"}, {"name": "host", "value": "fv-az803-956"}, {"name": "thread", "value": "2102-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_API_Suite.test_yopeso"}]}